<a href="https://colab.research.google.com/github/Aly0805/Assignment-6/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Algebra for ECE

###Laboratory 6: Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

###Objectives
At the end of this activity you will be able to:

1.   Be familiar with the fundamental matrix operations.
2.   Apply the operations to solve intemediate equations.
3.   Apply algebra in engineering solutions.



### Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Transposition

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

In [ ]:
A = np.array([
              [1, 2, 5],
              [5, -1, 0],
              [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

### Try to create your own matrix (you can try non-squares) to test transposition.

In [8]:
## Try out your code here.
A=np.array([
    [6,3,4],
    [9,0,6]        
])
A.shape

(2, 3)

In [9]:
np.transpose(A).shape

(3, 2)

In [11]:
A.T.shape

(3, 2)

In [12]:
AT = A.T
AT

array([[6, 9],
       [3, 0],
       [4, 6]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [4]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [5]:
np.array_equiv(X, Y)

False

In [6]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [7]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [8]:
X @ Y

array([[3, 4],
       [2, 2]])

In [9]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [2]:
D = np.array([
    [3,2,2],
    [3,1,3],
    [5,3,2]
])
E = np.array([
    [-2,0,5],
    [2,4,6],
    [7,4,3]
])

In [10]:
D @ E

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [11]:
D.dot(E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [12]:
np.matmul(D, E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [13]:
np.dot(D, E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [14]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
A = np.array([
              [9,2,1],
              [2,0,5],
              [0,3,2]
])
B = np.array([
              [1,4,7],
              [4,8,6],
              [6,3,1]
])
C = np.array([
              [3,5,4],
              [7,3,8],
              [9,5,1]
])

$A \cdot B \neq B \cdot A$

In [19]:
np.dot(A,B)

array([[23, 55, 76],
       [32, 23, 19],
       [24, 30, 20]])

In [20]:
np.dot(A,B)

array([[23, 55, 76],
       [32, 23, 19],
       [24, 30, 20]])

$A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [21]:
X = np.dot(B,C)
Y = np.dot(A,B)
Q = np.dot(A,X)
W = np.dot(Y,C)

In [22]:
print(Q)

[[1138  660  608]
 [ 428  324  331]
 [ 462  310  356]]


In [23]:
print(W)

[[1138  660  608]
 [ 428  324  331]
 [ 462  310  356]]


$A\cdot(B+C) = A\cdot B + A\cdot C$

In [25]:
D = B + C
print(D)

[[ 4  9 11]
 [11 11 14]
 [15  8  2]]


In [26]:
np.dot(A,D)

array([[ 73, 111, 129],
       [ 83,  58,  32],
       [ 63,  49,  46]])

In [27]:
E = np.dot(A,B)
print(E)

[[23 55 76]
 [32 23 19]
 [24 30 20]]


In [28]:
F = np.dot(A,C)
print(F)

[[50 56 53]
 [51 35 13]
 [39 19 26]]


In [29]:
E + F

array([[ 73, 111, 129],
       [ 83,  58,  32],
       [ 63,  49,  46]])

$(B+C)\cdot A = B\cdot A + C\cdot A$

In [30]:
np.dot((B+C),A)

array([[ 54,  41,  71],
       [121,  64,  94],
       [151,  36,  59]])

In [31]:
S = np.dot(B,A)
T = np.dot(C,A)

In [32]:
S + T

array([[ 54,  41,  71],
       [121,  64,  94],
       [151,  36,  59]])

$A\cdot I = A$

In [35]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
print(A)

[[9 2 1]
 [2 0 5]
 [0 3 2]]


In [37]:
np.dot(A,I)

array([[9., 2., 1.],
       [2., 0., 5.],
       [0., 3., 2.]])

$A\cdot \emptyset = \emptyset$

In [39]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.array_equal(a_dot_z,z_mat)

True

In [42]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Conclusion
  In this experiment, I was able to broaden my knowledge about the greater functions like Dot product, Inverse matrices etc. In python matrix can be implemented as array. Forming matrix from latter, gives the additional functionalities for performing various operations in matrix. These operations and array are defines as “numpy“. We were also able to apply the special property that was being discussed. By this experiment I can conclude that compared to manual compution, Python solved the following in a easy and faster way which can be used in the future lessons.

## Refences
[1] Linear Algebra Basics: Dot Product and Matrix Multiplication (2020). https://towardsdatascience.com/linear-algebra-basics-dot-product-and-matrix-multiplication-2a7624942810
[2] Python Program to find transpose of a matrix (2020). https://www.geeksforgeeks.org/python-program-to-find-transpose-of-a-matrix/
[3] Matrix manipulation in Python (2021): https://www.geeksforgeeks.org/matrix-manipulation-python/